blank_issues_enabled: true
contact_links:
  - name: Discord
    about: You can join the discussions on Discord.
    url: https://discord.com/invite/A6GSnKzazr
  - name: Twitter
    about: You can follow us on Twitter.
    url: https://x.com/getplura
